"""add sales contracts

Revision ID: 108a5129f5ec
Revises: c2745fdcd807
Create Date: 2025-12-08 14:53:56.864502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108a5129f5ec'
down_revision = 'c2745fdcd807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trailer_id', name='uq_sales_contract_trailer')
    )
    with op.batch_alter_table('sales_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_contract_contract_date'), ['contract_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_contract_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_contract_trailer_id'), ['trailer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_contract_trailer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_contract_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_contract_contract_date'))

    op.drop_table('sales_contract')
    # ### end Alembic commands ###
