"""add paid/shipped flags to sales_contract

Revision ID: 25697070af11
Revises: 52d5289c5940
Create Date: 2025-12-08 18:08:05.957926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25697070af11'
down_revision = '52d5289c5940'
branch_labels = None
depends_on = None



def upgrade():
    with op.batch_alter_table('sales_contract', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_paid',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0")
            )
        )
        batch_op.add_column(
            sa.Column(
                'is_shipped',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_contract', schema=None) as batch_op:
        batch_op.drop_column('is_shipped')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
