"""add customer doc fields

Revision ID: b9a80bf49d81
Revises: 25697070af11
Create Date: 2025-12-08 23:04:36.757147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a80bf49d81'
down_revision = '25697070af11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doc_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('doc_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('doc_issuer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('doc_issuer')
        batch_op.drop_column('doc_issue_date')
        batch_op.drop_column('doc_number')
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###
