"""add otss table

Revision ID: d7a447fda295
Revises: b9a80bf49d81
Create Date: 2025-12-08 23:09:12.709108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a447fda295'
down_revision = 'b9a80bf49d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('modification', sa.String(length=20), nullable=True),
    sa.Column('axle_count', sa.Integer(), nullable=True),
    sa.Column('full_weight_kg', sa.Integer(), nullable=True),
    sa.Column('payload_kg', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('platform_size', sa.String(length=100), nullable=True),
    sa.Column('body_size', sa.String(length=100), nullable=True),
    sa.Column('clearance_mm', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otts')
    # ### end Alembic commands ###
