"""add OTTS table

Revision ID: eb0efc471291
Revises: d7a447fda295
Create Date: 2025-12-08 23:30:46.955598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0efc471291'
down_revision = 'd7a447fda295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.alter_column('modification',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('axle_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index('idx_otts_mod_axles', ['modification', 'axle_count'], unique=False)
        batch_op.drop_column('valid_to')
        batch_op.drop_column('payload_kg')
        batch_op.drop_column('clearance_mm')
        batch_op.drop_column('category')
        batch_op.drop_column('code')
        batch_op.drop_column('platform_size')
        batch_op.drop_column('body_size')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('full_weight_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_weight_kg', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('body_size', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('platform_size', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('clearance_mm', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('payload_kg', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.DATE(), nullable=True))
        batch_op.drop_index('idx_otts_mod_axles')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('axle_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('modification',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
