"""initial trailers structure

Revision ID: f307927504ec
Revises: 
Create Date: 2025-12-08 13:54:32.894317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f307927504ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('TRAILER', 'COMPONENT', name='item_type'), nullable=False),
    sa.Column('article', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_length_mm', sa.Integer(), nullable=True),
    sa.Column('body_width_mm', sa.Integer(), nullable=True),
    sa.Column('board_height_mm', sa.Integer(), nullable=True),
    sa.Column('axle_count', sa.Integer(), nullable=True),
    sa.Column('wheel_radius', sa.String(length=10), nullable=True),
    sa.Column('has_tent', sa.Boolean(), nullable=True),
    sa.Column('hub_type', sa.String(length=50), nullable=True),
    sa.Column('size_external', sa.String(length=255), nullable=True),
    sa.Column('size_body', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_item_type'), ['item_type'], unique=False)

    op.create_table('otts_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axle_count', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'SOLD', 'RESERVED', 'IN_TRANSIT', 'DECOMMISSIONED', name='trailer_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailer_vin'), ['vin'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailer_vin'))

    op.drop_table('trailer')
    op.drop_table('warehouse')
    op.drop_table('otts_certificate')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_item_type'))
        batch_op.drop_index(batch_op.f('ix_item_article'))

    op.drop_table('item')
    # ### end Alembic commands ###
